[package]
name = "boursobank-dca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22", features = ["multipart"] }
tokio = { version = "1.33.0", features = ["full"] }
anyhow = { version = "1.0.75" }
regex = { version = "1.10.2" }
lazy_static = { version = "1.4.0" }
clap = { version = "4.4.6" }
rpassword = { version = "7.2.0" }